import type { Article } from '@/components/ArticlesClient'
import type { Album } from '@/components/AlbumsClient'

export const MOCK_ARTICLES: Article[] = [
  {
    id: 1,
    title: 'Charli XCX: Brat',
    title_ko: '찰리 XCX: Brat',
    author: 'Sheldon Pearce',
    source: 'pitchfork',
    source_url: 'https://pitchfork.com',
    thumbnail_url: 'https://placehold.co/800x400/1a1a1a/8a7a5a?text=brat',
    thumbnail_credit: 'Photo: Atlantic Records',
    published_at: '2024-06-07T00:00:00Z',
    category: 'review',
    content_en: `Charli XCX has always been a maximalist working in minimalist drag. The pop star's seventh album, *Brat*, strips her sound to its studs — four-on-the-floor kick drums, trebly synth stabs, and vocals processed until they're barely recognizable as human — and in doing so, she's made one of the year's most exhilarating records.\n\nThe album opens with "360," a hyperpop mission statement in which Charli declares herself "the moment," all braggadocio and self-awareness colliding in three and a half minutes. It sets the tone for what follows: a breathless sprint through club-ready anthems, heartfelt confessionals, and everything in between.\n\n"Von Dutch" is a standout, a crystalline piece of dance-pop that sounds like it was beamed in from a rave in 2006 and 2034 simultaneously. "Apple" leans into the album's running theme of self-examination, while "B2b" is a stunning piece of vulnerability disguised as a banger.`,
    content_ko: `찰리 XCX는 항상 미니멀리스트의 외양을 띤 맥시멀리스트였다. 그녀의 일곱 번째 앨범 *Brat*은 사운드를 뼈대까지 발라낸다 — 정박 킥 드럼, 날카로운 신스 스탭, 인간의 것인지 알아보기 힘들 정도로 처리된 보컬 — 그리고 바로 그렇게 함으로써 올해 가장 짜릿한 음반 중 하나를 만들어냈다.\n\n앨범은 "360"으로 시작한다. 자신이 "그 순간"임을 선언하는 하이퍼팝 선언문으로, 허풍과 자의식이 3분 반 안에 충돌한다. 이것이 이후에 펼쳐지는 것의 분위기를 설정한다: 클럽용 앤섬, 진심 어린 고백, 그리고 그 사이의 모든 것을 숨가쁘게 달려나가는 여정.\n\n"Von Dutch"는 2006년과 2034년 어딘가의 레이브에서 동시에 전송된 것 같은 수정처럼 맑은 댄스팝 명곡이다. "Apple"은 앨범의 자기 검열이라는 주제를 심화시키고, "B2b"는 클럽 뮤직으로 위장한 놀라운 취약성의 조각이다.`,
  },
  {
    id: 2,
    title: 'Billie Eilish: Hit Me Hard and Soft',
    title_ko: '빌리 아일리시: Hit Me Hard and Soft',
    author: 'Alphonse Pierre',
    source: 'pitchfork',
    published_at: '2024-05-17T00:00:00Z',
    category: 'review',
    content_en: `On her third studio album, Billie Eilish deepens her commitment to intimacy. Working again with her brother Finneas, she's made a record that exists at the exact threshold between whisper and cry, a place she knows better than anyone.\n\n"Lunch" opens with a confession so blunt it practically disarms: Eilish is in love, and she's not being subtle about it. But what follows is more nuanced — a collection of songs that trace the emotional logic of desire, loss, and the strange comfort of sadness.\n\nThe production is characteristically restrained, all negative space and careful placement. There are moments of surprising density — "The Greatest" builds to something almost symphonic — but even then, nothing is wasted.`,
    content_ko: `세 번째 정규 앨범에서 빌리 아일리시는 친밀함에 대한 헌신을 더욱 심화시킨다. 오빠 피니어스와 다시 작업하며 그녀는 속삭임과 울음의 정확한 경계에 존재하는 음반을 만들었다.\n\n"Lunch"는 너무나 솔직해서 거의 무장 해제시키는 고백으로 시작한다. 아일리시는 사랑에 빠졌고, 그것을 숨기지 않는다. 하지만 그다음에 이어지는 것은 더 미묘하다 — 욕망, 상실, 그리고 슬픔의 이상한 위로의 감정적 논리를 추적하는 노래들의 모음.\n\n프로덕션은 특유의 절제된 방식으로, 모두 여백과 신중한 배치로 이루어져 있다.`,
  },
  {
    id: 3,
    title: 'Kendrick Lamar: GNX',
    title_ko: '켄드릭 라마: GNX',
    author: 'Jonah Bromwich',
    source: 'stereogum',
    published_at: '2024-11-22T00:00:00Z',
    category: 'review',
    content_en: `Kendrick Lamar dropped *GNX* without warning on a Friday night, and the internet has not been the same since. Seven tracks, thirty-four minutes, no features, no apologies.\n\nIn the context of his now-legendary feud with Drake, the album lands like a victory lap that refuses to stop running. "Squabble Up" sets the terms immediately: this is someone who knows they've already won and is simply cataloguing the spoils.`,
    content_ko: `켄드릭 라마는 금요일 밤 예고 없이 *GNX*를 발표했고, 인터넷은 그 이후 달라졌다. 7트랙, 34분, 피처링 없음, 사과 없음.\n\n드레이크와의 전설적인 디스전의 맥락에서 이 앨범은 멈추기를 거부하는 우승 세레머니처럼 착지한다. "Squabble Up"은 즉시 조건을 설정한다: 이것은 이미 이겼다는 것을 알고 전리품을 목록화하고 있는 누군가의 이야기다.`,
  },
  {
    id: 4,
    title: 'Sabrina Carpenter: Short n\' Sweet',
    title_ko: '사브리나 카펜터: Short n\' Sweet',
    author: 'Cat Zhang',
    source: 'pitchfork',
    published_at: '2024-08-23T00:00:00Z',
    category: 'review',
    content_en: `Sabrina Carpenter has spent years being underestimated. *Short n' Sweet* is her response — a concise, immaculately crafted pop record that doesn't waste a second of its thirty-six minutes.\n\nThe singles already established her as one of the sharpest pop minds working today. "Espresso" is a masterclass in economy: a song that says everything it needs to say in two and a half minutes and not a word more.`,
    content_ko: `사브리나 카펜터는 수년간 과소평가를 받아왔다. *Short n' Sweet*은 그녀의 응답이다 — 36분 중 단 1초도 낭비하지 않는 간결하고 흠잡을 데 없이 제작된 팝 음반.\n\n싱글들은 이미 그녀를 현재 활동 중인 가장 예리한 팝 작가 중 한 명으로 확립시켰다. "Espresso"는 경제성의 교과서다.`,
  },
  {
    id: 5,
    title: 'Kim Gordon: The Collective',
    title_ko: '김 고든: The Collective',
    author: 'Madison Bloom',
    source: 'pitchfork',
    published_at: '2024-03-08T00:00:00Z',
    category: 'review',
    content_en: `Kim Gordon's second solo album arrives six years after her memoir *Girl in a Band* and four years after *No Home Record*, and it finds her in an even more confrontational mode. Working with producer Justin Raisen, she's made a record that sounds like TikTok and doom metal colliding in slow motion.\n\nThe production is genuinely strange — trap hi-hats beneath sheets of distorted guitar, spoken word fragments over blown-out 808s — but Gordon navigates it with her characteristic authority.`,
    content_ko: `킴 고든의 두 번째 솔로 앨범은 회고록 *Girl in a Band*로부터 6년, *No Home Record*로부터 4년 만에 나왔으며, 더욱 대립적인 방식으로 그녀를 발견한다. 프로듀서 저스틴 레이센과 작업하며 그녀는 틱톡과 둠 메탈이 슬로우 모션으로 충돌하는 것 같은 음반을 만들었다.`,
  },
]

export const MOCK_ALBUMS: Album[] = [
  { id: '1', title: 'Brat', artist: 'Charli XCX', artwork_url: 'https://placehold.co/300x300/86ff00/000000?text=brat', release_date: '2024-06-07', region: '해외', album_type: '정규', is_featured: true },
  { id: '2', title: 'Hit Me Hard and Soft', artist: 'Billie Eilish', artwork_url: 'https://placehold.co/300x300/1a1a1a/8a7a5a?text=HMAHS', release_date: '2024-05-17', region: '해외', album_type: '정규', is_featured: false },
  { id: '3', title: 'GNX', artist: 'Kendrick Lamar', artwork_url: 'https://placehold.co/300x300/2a1800/E8D5A0?text=GNX', release_date: '2024-11-22', region: '해외', album_type: '정규', is_featured: true },
  { id: '4', title: "Short n' Sweet", artist: 'Sabrina Carpenter', artwork_url: 'https://placehold.co/300x300/f5c2d0/000000?text=S%26S', release_date: '2024-08-23', region: '해외', album_type: '정규', is_featured: false },
  { id: '5', title: 'The Collective', artist: 'Kim Gordon', artwork_url: 'https://placehold.co/300x300/0a0a0a/E8D5A0?text=TC', release_date: '2024-03-08', region: '해외', album_type: '정규', is_featured: false },
  { id: '6', title: 'Imaginal Disk', artist: 'Magdalena Bay', artwork_url: 'https://placehold.co/300x300/6a0dad/ffffff?text=ID', release_date: '2024-09-23', region: '해외', album_type: '정규', is_featured: true },
  { id: '7', title: 'Manning Fireworks', artist: 'MJ Lenderman', artwork_url: 'https://placehold.co/300x300/3d2500/E8D5A0?text=MF', release_date: '2024-09-06', region: '해외', album_type: '정규', is_featured: false },
  { id: '8', title: 'Chromakopia', artist: 'Tyler, the Creator', artwork_url: 'https://placehold.co/300x300/4a3728/E8D5A0?text=C', release_date: '2024-10-28', region: '해외', album_type: '정규', is_featured: false },
  { id: '9', title: '사건의 지평선', artist: '윤하', artwork_url: 'https://placehold.co/300x300/000033/87CEEB?text=윤하', release_date: '2022-01-24', region: '국내', album_type: 'EP', is_featured: false },
  { id: '10', title: 'Fearless (Taylor\'s Version)', artist: 'Taylor Swift', artwork_url: 'https://placehold.co/300x300/d4af37/000000?text=TV', release_date: '2021-04-09', region: '해외', album_type: '정규', is_featured: false },
  { id: '11', title: 'MOODSWINGS IN THIS ORDER', artist: 'RINI', artwork_url: 'https://placehold.co/300x300/1a0e00/E8D5A0?text=MITO', release_date: '2024-02-16', region: '해외', album_type: 'EP', is_featured: false },
  { id: '12', title: 'Bright Future', artist: 'Adrianne Lenker', artwork_url: 'https://placehold.co/300x300/2c1810/E8D5A0?text=BF', release_date: '2024-03-22', region: '해외', album_type: '정규', is_featured: false },
]
